# Generated by Django 3.2.12 on 2022-07-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='ipaddress',
            field=models.CharField(default='0.0.0.0', max_length=15, verbose_name='IP address'),
        ),
    ]
