# Generated by Django 4.0.5 on 2022-07-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_ipaddress_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='kerio_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description in KerioControl '),
        ),
    ]
