# Generated by Django 4.0.5 on 2022-08-16 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_ipaddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='kerio_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.keriogroup'),
        ),
    ]
