# Generated by Django 4.0.5 on 2022-08-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_ipaddress_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipaddress',
            old_name='kerio_group',
            new_name='router_group',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='in_kerio',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='kerio_description',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='kerio_id',
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='in_router',
            field=models.BooleanField(default=False, verbose_name='Applied in Router'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='router_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description in Router '),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='router_id',
            field=models.CharField(blank=True, default=None, max_length=5, null=True, verbose_name='ID in Router'),
        ),
    ]
