# Generated by Django 4.0.5 on 2022-08-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_ipaddress_kerio_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='kerio_id',
            field=models.CharField(max_length=5, null=True, unique=True, verbose_name='ID in KerioControl'),
        ),
    ]
