# Generated by Django 4.0.5 on 2022-08-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=1000, verbose_name='Лог')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
